version: "3.7"

services:

  web:
    build:
      context: ./
      dockerfile: conf/Dockerfile
    container_name: powercheck-web
    image: ${DOCKER_COMPOSE_IMAGE}
    ports:
      - 80:80
    networks:
      powercheck-web:
        aliases:
          - ${API_HOSTNAME}
      powercheck-db:
      
  db:
    container_name: powercheck-db
    image: mongo:6.0.2
    volumes: 
      - ${ROOT_PATH}/volumes/database:/data/db
    networks: 
      powercheck-db:
        aliases: 
          - ${MONGODB_HOSTNAME}

networks: 
  powercheck-web:
    name: powercheck-web
  powercheck-db:
    name: powercheck-db
